// Generated by CoffeeScript 1.6.3
var cli, config, fs, logger, nodprof, nopt, path, pkg, profiler, server, utils, _;

fs = require("fs");

path = require("path");

nopt = require("nopt");

_ = require("underscore");

pkg = require("../../package.json");

nodprof = require("../..");

utils = require("../common/utils");

logger = require("../common/logger");

config = require("./config");

profiler = require("./profiler");

server = require("./server");

cli = exports;

cli.run = function() {
  var args, _ref;
  _ref = config.getConfiguration(process.argv.slice(2)), args = _ref.args, config = _ref.config;
  logger.setDebug(config.debug);
  logger.setVerbose(config.verbose);
  if (config.serve) {
    return server.run(config);
  } else {
    return profiler.run({
      args: args,
      config: config
    });
  }
};

if (require.main === module) {
  cli.run();
}
