// Generated by CoffeeScript 1.6.3
var WWWDIR, express, http, logger, middleware, path, pkg, utils;

http = require("http");

path = require("path");

express = require("express");

pkg = require("../../package.json");

utils = require("../common/utils");

logger = require("../common/logger");

middleware = require("./middleware");

WWWDIR = path.join(__dirname, "../../www");

exports.run = function(config) {
  var app, favIcon;
  favIcon = path.join(WWWDIR, "images/icon-032.png");
  app = express();
  app.on("error", function(error) {
    return logger.log(error);
  });
  app.use(express.favicon(favIcon));
  app.use("/", middleware(config));
  app.use(express.errorHandler({
    dumpExceptions: true
  }));
  logger.log("starting server at http://localhost:" + config.port);
  logger.dlog("configuration: " + (utils.JL(config)));
  return app.listen(config.port);
};
