// Generated by CoffeeScript 1.6.3
var DateStarted, Profiling, nodprof, nodprof_natives, pkg;

nodprof_natives = require("bindings")("nodprof_natives.node");

nodprof = exports;

pkg = require("../package.json");

nodprof.version = pkg.version;

Profiling = false;

DateStarted = null;

nodprof.middleware = require("./node/middleware");

nodprof.profileStart = function() {
  if (Profiling) {
    return;
  }
  Profiling = true;
  DateStarted = new Date;
  nodprof_natives.profilerStart();
};

nodprof.profileStop = function() {
  var result;
  if (!Profiling) {
    return null;
  }
  Profiling = false;
  result = nodprof_natives.profilerStop();
  result.dateStarted = DateStarted;
  result.dateStopped = new Date;
  return result;
};

nodprof.isProfiling = function() {
  return Profiling;
};

nodprof.heapSnapshot = function() {
  var date, result;
  date = new Date;
  result = nodprof_natives.heapSnapShotTake();
  result.date = date;
  return result;
};
